cancelled:
  status: false

scenario:
  type: preprod
  name: Scénario
  progress: 5

capture:
  type: preprod
  name: Pré-production
  progress: 1

montage:
  type: video
  name: Tournage et Capture
  progress: 1

dubbing:
  type: video
  name: Montage et VFX
  progress: 1

mixing:
  type: audio
  name: Doublage et Mixage
  progress: 1
