cancelled:
  status: false

scenario:
  type: preprod
  name: Scénario
  progress: 100

capture:
  type: preprod
  name: Pré-production (storyboard, forge...)
  progress: 85

montage:
  type: video
  name: Tournage et Capture
  progress: 80

dubbing:
  type: video
  name: Montage et Effets visuels
  progress: 100

mixing:
  type: audio
  name: Doublage et Mixage audio
  progress: 10
