cancelled:
  status: false

scenario:
  type: preprod
  name: Scénario
  progress: 5

capture:
  type: preprod
  name: Pré-production (storyboard, forge...)
  progress: 1

montage:
  type: video
  name: Tournage et Capture
  progress: 1

dubbing:
  type: video
  name: Montage et Effets visuels
  progress: 1

mixing:
  type: audio
  name: Doublage et Mixage audio
  progress: 1
