cancelled:
  status: false

scenario:
  type: preprod
  name: Scénario
  progress: 100

capture:
  type: video
  name: Tournage
  progress: 45

montage:
  type: video
  name: Montage
  progress: 40

dubbing:
  type: audio
  name: Doublage
  progress: 100

mixing:
  type: audio
  name: Mixage audio
  progress: 5
