cancelled:
  status: false

scenario:
  type: preprod
  name: Scénario
  progress: 100

capture:
  type: video
  name: Tournage
  progress: 70

montage:
  type: video
  name: Montage
  progress: 60

dubbing:
  type: audio
  name: Doublage
  progress: 0

mixing:
  type: audio
  name: Mixage audio
  progress: 35
