cancelled:
  status: false

scenario:
  type: preprod
  name: Scénario
  progress: 80

capture:
  type: video
  name: Tournage
  progress: 1

montage:
  type: video
  name: Montage
  progress: 1

dubbing:
  type: audio
  name: Doublage
  progress: 1

mixing:
  type: audio
  name: Mixage audio
  progress: 1
